class Language {
  final String code;
  final String nameEn;
  final String nameFr;
  const Language({required this.code, required this.nameEn, required this.nameFr});
}

const kPriorityLanguages = [
  Language(code: 'fr', nameEn: 'French', nameFr: 'Français'),
  Language(code: 'en', nameEn: 'English', nameFr: 'Anglais'),
  Language(code: 'de', nameEn: 'German', nameFr: 'Allemand'),
  Language(code: 'es', nameEn: 'Spanish', nameFr: 'Espagnol'),
  Language(code: 'zh', nameEn: 'Chinese', nameFr: 'Chinois'),
  Language(code: 'ar', nameEn: 'Arabic', nameFr: 'Arabe'),
  Language(code: 'pt', nameEn: 'Portuguese', nameFr: 'Portugais'),
];

const kAllLanguages = [
  ...kPriorityLanguages,
  Language(code: 'af', nameEn: 'Afrikaans', nameFr: 'Afrikaans'),
  Language(code: 'sq', nameEn: 'Albanian', nameFr: 'Albanais'),
  Language(code: 'am', nameEn: 'Amharic', nameFr: 'Amharique'),
  Language(code: 'hy', nameEn: 'Armenian', nameFr: 'Arménien'),
  Language(code: 'az', nameEn: 'Azerbaijani', nameFr: 'Azerbaïdjanais'),
  Language(code: 'eu', nameEn: 'Basque', nameFr: 'Basque'),
  Language(code: 'be', nameEn: 'Belarusian', nameFr: 'Biélorusse'),
  Language(code: 'bn', nameEn: 'Bengali', nameFr: 'Bengali'),
  Language(code: 'bs', nameEn: 'Bosnian', nameFr: 'Bosniaque'),
  Language(code: 'bg', nameEn: 'Bulgarian', nameFr: 'Bulgare'),
  Language(code: 'ca', nameEn: 'Catalan', nameFr: 'Catalan'),
  Language(code: 'ceb', nameEn: 'Cebuano', nameFr: 'Cebuano'),
  Language(code: 'co', nameEn: 'Corsican', nameFr: 'Corse'),
  Language(code: 'hr', nameEn: 'Croatian', nameFr: 'Croate'),
  Language(code: 'cs', nameEn: 'Czech', nameFr: 'Tchèque'),
  Language(code: 'da', nameEn: 'Danish', nameFr: 'Danois'),
  Language(code: 'nl', nameEn: 'Dutch', nameFr: 'Néerlandais'),
  Language(code: 'eo', nameEn: 'Esperanto', nameFr: 'Espéranto'),
  Language(code: 'et', nameEn: 'Estonian', nameFr: 'Estonien'),
  Language(code: 'fi', nameEn: 'Finnish', nameFr: 'Finnois'),
  Language(code: 'gl', nameEn: 'Galician', nameFr: 'Galicien'),
  Language(code: 'ka', nameEn: 'Georgian', nameFr: 'Géorgien'),
  Language(code: 'el', nameEn: 'Greek', nameFr: 'Grec'),
  Language(code: 'gu', nameEn: 'Gujarati', nameFr: 'Gujarati'),
  Language(code: 'ht', nameEn: 'Haitian Creole', nameFr: 'Créole haïtien'),
  Language(code: 'ha', nameEn: 'Hausa', nameFr: 'Haoussa'),
  Language(code: 'haw', nameEn: 'Hawaiian', nameFr: 'Hawaïen'),
  Language(code: 'he', nameEn: 'Hebrew', nameFr: 'Hébreu'),
  Language(code: 'hi', nameEn: 'Hindi', nameFr: 'Hindi'),
  Language(code: 'hu', nameEn: 'Hungarian', nameFr: 'Hongrois'),
  Language(code: 'id', nameEn: 'Indonesian', nameFr: 'Indonésien'),
  Language(code: 'ga', nameEn: 'Irish', nameFr: 'Irlandais'),
  Language(code: 'it', nameEn: 'Italian', nameFr: 'Italien'),
  Language(code: 'ja', nameEn: 'Japanese', nameFr: 'Japonais'),
  Language(code: 'jv', nameEn: 'Javanese', nameFr: 'Javanais'),
  Language(code: 'kn', nameEn: 'Kannada', nameFr: 'Kannada'),
  Language(code: 'kk', nameEn: 'Kazakh', nameFr: 'Kazakh'),
  Language(code: 'km', nameEn: 'Khmer', nameFr: 'Khmer'),
  Language(code: 'ko', nameEn: 'Korean', nameFr: 'Coréen'),
  Language(code: 'ku', nameEn: 'Kurdish', nameFr: 'Kurde'),
  Language(code: 'lo', nameEn: 'Lao', nameFr: 'Laotien'),
  Language(code: 'la', nameEn: 'Latin', nameFr: 'Latin'),
  Language(code: 'lv', nameEn: 'Latvian', nameFr: 'Letton'),
  Language(code: 'lt', nameEn: 'Lithuanian', nameFr: 'Lituanien'),
  Language(code: 'lb', nameEn: 'Luxembourgish', nameFr: 'Luxembourgeois'),
  Language(code: 'mk', nameEn: 'Macedonian', nameFr: 'Macédonien'),
  Language(code: 'mg', nameEn: 'Malagasy', nameFr: 'Malgache'),
  Language(code: 'ms', nameEn: 'Malay', nameFr: 'Malais'),
  Language(code: 'ml', nameEn: 'Malayalam', nameFr: 'Malayâlam'),
  Language(code: 'mt', nameEn: 'Maltese', nameFr: 'Maltais'),
  Language(code: 'mi', nameEn: 'Maori', nameFr: 'Maori'),
  Language(code: 'mr', nameEn: 'Marathi', nameFr: 'Marathi'),
  Language(code: 'mn', nameEn: 'Mongolian', nameFr: 'Mongol'),
  Language(code: 'my', nameEn: 'Myanmar (Burmese)', nameFr: 'Birman'),
  Language(code: 'ne', nameEn: 'Nepali', nameFr: 'Népalais'),
  Language(code: 'no', nameEn: 'Norwegian', nameFr: 'Norvégien'),
  Language(code: 'ny', nameEn: 'Nyanja', nameFr: 'Nyanja'),
  Language(code: 'or', nameEn: 'Odia', nameFr: 'Odia'),
  Language(code: 'ps', nameEn: 'Pashto', nameFr: 'Pachtou'),
  Language(code: 'fa', nameEn: 'Persian', nameFr: 'Persan'),
  Language(code: 'pl', nameEn: 'Polish', nameFr: 'Polonais'),
  Language(code: 'pa', nameEn: 'Punjabi', nameFr: 'Pendjabi'),
  Language(code: 'ro', nameEn: 'Romanian', nameFr: 'Roumain'),
  Language(code: 'ru', nameEn: 'Russian', nameFr: 'Russe'),
  Language(code: 'sm', nameEn: 'Samoan', nameFr: 'Samoan'),
  Language(code: 'gd', nameEn: 'Scots Gaelic', nameFr: 'Gaélique écossais'),
  Language(code: 'sr', nameEn: 'Serbian', nameFr: 'Serbe'),
  Language(code: 'st', nameEn: 'Sesotho', nameFr: 'Sotho du Sud'),
  Language(code: 'sn', nameEn: 'Shona', nameFr: 'Shona'),
  Language(code: 'sd', nameEn: 'Sindhi', nameFr: 'Sindhi'),
  Language(code: 'si', nameEn: 'Sinhala', nameFr: 'Cingalais'),
  Language(code: 'sk', nameEn: 'Slovak', nameFr: 'Slovaque'),
  Language(code: 'sl', nameEn: 'Slovenian', nameFr: 'Slovène'),
  Language(code: 'so', nameEn: 'Somali', nameFr: 'Somali'),
  Language(code: 'su', nameEn: 'Sundanese', nameFr: 'Soundanais'),
  Language(code: 'sw', nameEn: 'Swahili', nameFr: 'Swahili'),
  Language(code: 'sv', nameEn: 'Swedish', nameFr: 'Suédois'),
  Language(code: 'tl', nameEn: 'Filipino', nameFr: 'Filipino'),
  Language(code: 'tg', nameEn: 'Tajik', nameFr: 'Tadjik'),
  Language(code: 'ta', nameEn: 'Tamil', nameFr: 'Tamoul'),
  Language(code: 'tt', nameEn: 'Tatar', nameFr: 'Tatar'),
  Language(code: 'te', nameEn: 'Telugu', nameFr: 'Telugu'),
  Language(code: 'th', nameEn: 'Thai', nameFr: 'Thaï'),
  Language(code: 'tr', nameEn: 'Turkish', nameFr: 'Turc'),
  Language(code: 'tk', nameEn: 'Turkmen', nameFr: 'Turkmène'),
  Language(code: 'uk', nameEn: 'Ukrainian', nameFr: 'Ukrainien'),
  Language(code: 'ur', nameEn: 'Urdu', nameFr: 'Ourdou'),
  Language(code: 'ug', nameEn: 'Uyghur', nameFr: 'Ouïghour'),
  Language(code: 'uz', nameEn: 'Uzbek', nameFr: 'Ouzbek'),
  Language(code: 'vi', nameEn: 'Vietnamese', nameFr: 'Vietnamien'),
  Language(code: 'cy', nameEn: 'Welsh', nameFr: 'Gallois'),
  Language(code: 'xh', nameEn: 'Xhosa', nameFr: 'Xhosa'),
  Language(code: 'yi', nameEn: 'Yiddish', nameFr: 'Yiddish'),
  Language(code: 'yo', nameEn: 'Yoruba', nameFr: 'Yoruba'),
  Language(code: 'zu', nameEn: 'Zulu', nameFr: 'Zoulou'),
];
