import { serve } from 'https://deno.land/std@0.177.0/http/server.ts'
import { corsHeaders } from '../_shared/cors.ts'
import { supabaseAdmin } from '../_shared/supabase_admin.ts'

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const { reportId, userId } = await req.json()

    if (!reportId || !userId) {
      return new Response(JSON.stringify({ error: 'Missing required fields' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      })
    }

    // Fetch scan report (RLS enforcement via user_id check)
    const { data: report, error: reportError } = await supabaseAdmin
      .from('scan_reports')
      .select('*')
      .eq('id', reportId)
      .eq('user_id', userId)
      .single()

    if (reportError || !report) {
      return new Response(JSON.stringify({ error: 'Report not found or access denied' }), {
        status: 404,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      })
    }

    // Fetch document name
    const { data: document } = await supabaseAdmin
      .from('documents')
      .select('name')
      .eq('id', report.document_id)
      .maybeSingle()

    const documentName = document?.name ?? 'Unknown Document'
    const scanDate = new Date(report.created_at).toLocaleDateString('en-GB', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    })

    const similarityPct = report.similarity_pct ?? 0
    const sources: any[] = JSON.parse(report.sources ?? '[]')

    // Colour based on similarity
    const color =
      similarityPct < 30 ? '#43A047' : similarityPct < 70 ? '#FB8C00' : '#E53935'
    const riskLabel =
      similarityPct < 30
        ? 'Low Risk — Likely Original'
        : similarityPct < 70
        ? 'Medium Risk — Review Required'
        : 'High Risk — Significant Matches Found'

    const sourcesHtml = sources
      .map(
        (s) => `
      <div style="border:1px solid #e0e0e0; border-radius:8px; padding:12px; margin-bottom:8px;">
        <div style="display:flex; justify-content:space-between; align-items:center;">
          <div style="background:${color}; color:white; border-radius:50%; width:40px; height:40px;
               display:flex; align-items:center; justify-content:center; font-weight:bold; font-size:12px;">
            ${Math.round(s.matchedPercent)}%
          </div>
          <div style="flex:1; margin-left:12px;">
            <div style="font-weight:600; font-size:14px;">${s.title ?? s.url}</div>
            <div style="color:#6B7C8D; font-size:12px;">${s.url}</div>
          </div>
        </div>
      </div>`
      )
      .join('')

    const htmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>VeriScript Originality Report</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
           margin: 0; padding: 24px; background: #F0F6FB; color: #0F1E2D; }
    .header { background: #1A3C5E; color: white; padding: 24px; border-radius: 12px; margin-bottom: 24px; }
    .header h1 { margin: 0; font-size: 24px; }
    .header p  { margin: 4px 0 0; color: #2BBFAA; font-size: 14px; }
    .score-card { background: white; border-radius: 12px; padding: 24px; text-align: center; margin-bottom: 24px; }
    .score { font-size: 72px; font-weight: 800; color: ${color}; }
    .risk-label { background: ${color}22; color: ${color}; padding: 6px 16px;
                  border-radius: 20px; display: inline-block; font-weight: 600; margin-top: 8px; }
    .sources-section { background: white; border-radius: 12px; padding: 24px; }
    .footer { text-align: center; color: #6B7C8D; font-size: 12px; margin-top: 24px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>VeriScript</h1>
    <p>Originality Report</p>
  </div>
  <div class="score-card">
    <div style="font-size:16px; color:#6B7C8D;">${documentName}</div>
    <div style="font-size:13px; color:#6B7C8D; margin-bottom:16px;">${scanDate}</div>
    <div class="score">${Math.round(similarityPct)}%</div>
    <div style="color:#6B7C8D; font-size:14px; margin-top:4px;">Similarity Score</div>
    <div class="risk-label">${riskLabel}</div>
  </div>
  <div class="sources-section">
    <h2 style="margin:0 0 16px;">Matched Sources (${sources.length})</h2>
    ${sourcesHtml || '<p style="color:#6B7C8D;">No specific sources identified</p>'}
  </div>
  <div class="footer">Generated by VeriScript · ${scanDate}</div>
</body>
</html>`

    return new Response(JSON.stringify({ htmlContent }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })
  } catch (error) {
    console.error('export-report-pdf error:', error)
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })
  }
})
